modLoader="javafml"
loaderVersion="[47,)"
license="Academic Free License v3.0"

[[mods]]
modId="goldenstrawberry"
version="1.3.0"
displayName="GoldenStrawberry"
displayURL="https://github.com/sobakinmontazer/GoldenStrawberry"
credits="Hi!"
authors="ForZzy_FZ, SobakinMontazer"

[[dependencies.goldenstrawberry]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"




